name: main-test-debug

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: install-deps
      run: sudo apt-get install -y cppcheck libgtest-dev
    - uses: actions/checkout@v1
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
    - name: make
      run: cd build && make
    - name: run-test
      run: ./build/main
    - name: run-check
      run: cd build && cppcheck --project=compile_commands.json --enable=warning,style,performance,portability --error-exitcode=1
    - name: display-cov
      run: cd build && gcov -H CMakeFiles/main.dir/main.cpp.gcda | head -2
